name: CI
on: [push,pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name: Setup Node.js
    uses: action/setup-node@v1
    with:
      node-version: '14'
    - name: Install Dependencies
    run: npm install
    - name: Build
    run: npm run build
